### ISSUE TITLE
Remove "packages" section from main page

### ISSUE THREAD

**Issue by elijahr** [asdf-community/asdf-nim#2]
@smorimoto when you get a chance, can you remove the "Packages" section from the main page?

These are docker images used internally by the arm/ppc builds via run-on-arch-action. It's not a problem to have them there, they just clutter the page.

![image](https://user-images.githubusercontent.com/153711/103756012-5dc84880-4fd4-11eb-9933-a4634645e972.png)

**Comment by elijahr** [comment]
Also - what do you think of creating an `asdf-community` community on gitter.im so folks can ask questions and get help for the asdf plugins in this org?

**Comment by smorimoto** [comment]
Done.

**Comment by smorimoto** [comment]
I don't use Gitter, so I don't know about that, but I also think it's good to have such a chat on Discord or Matrix.

**Comment by elijahr** [comment]
Cool - I don't have much experience with any of them- mostly with gitter. One thing I like about it is you can get email notifications when there is activity in a room - so it can be both a chat room in real-time, but also just a place for more asynchronous communication.

**Comment by elijahr** [comment]
Like for instance https://gitter.im/nim-lang/Nim is pretty active

**Comment by smorimoto** [comment]
I wouldn't use Gitter because I don't want to increase platforms that I need to check, but things like Discord are a good option for the tech community, not only the game.

**Comment by smorimoto** [comment]
With Matrix, I can make such a room. And it can be bridged with Gitter, but I don't think I can deal with it even if I make one at this very moment, so I will re-think about it again after I get enough spare time.
