### ISSUE TITLE
Fails to install Nim 1.4.6

### ISSUE THREAD

**Issue by rikusen0335** [asdf-community/asdf-nim#4]
**Describe the bug**
```sh
❯ asdf install nim 1.4.6

# Installing
# ↳ Running install.sh … 
# 😱 Exited with status 1:

/home/rikusen/.asdf/plugins/nim/bin/../lib/utils.bash: line 549: ASDF_DOWNLOAD_PATH: unbound variable
/home/rikusen/.asdf/plugins/nim/bin/../lib/utils.bash: line 750: ASDF_DOWNLOAD_PATH: unbound variable
/home/rikusen/.asdf/plugins/nim/bin/install: line 38: ASDF_DOWNLOAD_PATH: unbound variable

# Cleaning up install directory…
```

**Steps to reproduce**
Just trying to this: `asdf install nim 1.4.6`

**Expected behavior**
asdf-vm installs nim through the plugin.

**Screenshots**
Nothing

**Additional context**
Nothing

**Comment by smorimoto** [comment]
Yo @elijahr, can you take a look at this?

**Comment by rikusen0335** [comment]
Sorry, I noticed I have to do this in first before installing: `asdf nim install-deps`
It's my fault, I didn't update asdf yet from `v0.7.6-6207e42`, well gonna try this^

**Comment by smorimoto** [comment]
Unfortunately, 90% of developers don't read the README 😅

**Comment by rikusen0335** [comment]
So there's word "RTFM" and of cource I'm with it 🙄
Sorry man
