### ISSUE TITLE
`nimble` shows unbound variable error

### ISSUE THREAD

**Issue by rikusen0335** [asdf-community/asdf-nim#5]
**Describe the bug**

`nimble` shows `/path/to/home/.asdf/plugins/nim/shims/nimble: line 24: $1: unbound variable` and nimble's help.
`nimble -h` shows nimble's help.

**Steps to reproduce**

Just type `nimble`

**Expected behavior**

`nimble` just shows nimble's help

**Screenshots**

![image](https://user-images.githubusercontent.com/19174234/119629515-0aeb1280-be49-11eb-99a2-aacd17d91be1.png)

**Additional context**

**Comment by elijahr** [comment]
@rikusen0335 thank you for the report! I have a fix in the works.
